### PR TITLE
add .Xresources

### PR DESCRIPTION
**Pull request by roryrjb**
Hey @strange,

Not sure if you are interested in adding this to your repo, but this is what I'm now using locally with __rxvt__, alongside the Vim colorscheme.

### CODE REVIEW

**Comment by roryrjb** [comment]
Screenshot at 2020-12-11 08-03-03

**Comment by strange** [comment]
Super-awesome!

**Comment by strange** [comment]
I don't think rxvt has true color support. I do some automated approximations when converting 32-bit to 8-bit. Would probably get better results by just using 16 colors and setting the correct theme in the terminal emulator.

Check out [Kitty](https://sw.kovidgoyal.net/kitty/) if you want a neat emulator with support for 32-bit colors and slightly less input lag.

**Comment by roryrjb** [comment]
@strange thanks. Yeah I realise it's not exact, but I purposefully choose to use xterm/rxvt over more modern alternatives ;)

**Pull request merged**
